"""Atributos faltantes em profile, blog e forum

Revision ID: 0b87193b6bf0
Revises: 96fca188d3e3
Create Date: 2026-06-10 18:48:09.103356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b87193b6bf0'
down_revision = '96fca188d3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handler', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(None, ['handler'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('handler')

    with op.batch_alter_table('forum_posts', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
