"""Atributos faltantes em profile, blog e forum

Revision ID: bf1e87fdbdc2
Revises: 0b87193b6bf0
Create Date: 2026-06-10 18:54:12.279287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1e87fdbdc2'
down_revision = '0b87193b6bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.String(length=64), nullable=False))
        batch_op.drop_constraint(batch_op.f('profiles_handler_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['handle'])
        batch_op.drop_column('handler')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handler', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('profiles_handler_key'), ['handler'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('handle')

    # ### end Alembic commands ###
